# Generated by Django 3.0.5 on 2020-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('brand', models.CharField(max_length=20, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '汽车',
                'verbose_name_plural': '汽车',
                'db_table': 'tb_car',
            },
        ),
    ]
